language: php

php:
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer require --no-update satooshi/php-coveralls:dev-master sensiolabs/security-checker:dev-master
  - composer update --dev --no-interaction
  - sudo easy_install Pygments

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
  - php vendor/bin/security-checker security:check composer.lock

after_script:
  - php vendor/bin/coveralls

after_success:
  - composer require --no-update composer/composer:*@dev
  - composer require kzykhys/markbench:*@dev
  - vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=blank
  - vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=default
  - vendor/bin/markbench benchmark --parser=kzykhys/ciconia --profile=github-sample
