language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer require --no-update satooshi/php-coveralls:dev-master sensiolabs/security-checker:dev-master
  - travis_retry composer update --dev --no-interaction
  - sudo easy_install Pygments

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
  - php vendor/bin/security-checker security:check composer.lock

after_script:
  - php vendor/bin/coveralls
  - git clone git@github.com:jgm/CommonMark.git
  - python CommonMark/test/spec_tests.py --program bin/markdown

after_success:
  - composer require --no-update composer/composer:*@dev
  - composer require kzykhys/markbench:*@dev
  - vendor/bin/markbench benchmark --parser=fluxbb/markdown --profile=blank
  - vendor/bin/markbench benchmark --parser=fluxbb/markdown --profile=default
  - vendor/bin/markbench benchmark --parser=fluxbb/markdown --profile=github-sample
