language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer require --no-update satooshi/php-coveralls:dev-master sensiolabs/security-checker:dev-master
  - travis_retry composer update --dev --no-interaction
  - sudo easy_install Pygments
  - git clone https://github.com/jgm/CommonMark.git
  - chmod a+x bin/markdown

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
  - cd CommonMark && python test/spec_tests.py --program ../bin/markdown
  - php vendor/bin/security-checker security:check composer.lock

after_script:
  - php vendor/bin/coveralls

after_success:
  - composer require --no-update composer/composer:*@dev
  - composer require kzykhys/markbench:*@dev
  - vendor/bin/markbench benchmark --parser=fluxbb/markdown --profile=blank
  - vendor/bin/markbench benchmark --parser=fluxbb/markdown --profile=default
  - vendor/bin/markbench benchmark --parser=fluxbb/markdown --profile=github-sample

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b85fb5b2dfad0466dee2
    on_success: always
    on_failure: always
    on_start: false
